//
// SoundFont
//
// Created by Brad Howes
// Copyright (c) 2018 Brad Howes. All rights reserved.
//
// NOTE: this file was autogenerated by the `catalog.py` script.

let UserBankSoundFont = SoundFont("User Bank", fileName: "RolandNicePiano", [
    Patch("Nice Piano",                    0,   1,   0),
])
