SoundFontInfoLib: SF2::Render::InstrumentZone Class Reference
SF2::Render::InstrumentZone Class Reference
A specialization of a Zone for an Instrument.
#include <InstrumentZone.hpp>
Inherits SF2::Render::Zone.
Public Member Functions
InstrumentZone (const IO::File &file, const Entity::Bag &bag)
Construct new zone from entity in file.
void apply (Voice::State &state) const
Apply the zone generator values to the given voice state.
const Render::Sample::CanonicalBuffer * sampleBuffer () const
Public Member Functions inherited from SF2::Render::Zone
const MIDIRange & keyRange () const
const MIDIRange & velocityRange () const
const GeneratorCollection & generators () const
const ModulatorCollection & modulators () const
bool isGlobal () const
bool appliesTo (int key, int velocity) const
Determines if this zone applies to a given MIDI key/velocity pair.
Additional Inherited Members
Public Types inherited from SF2::Render::Zone
using GeneratorCollection = IO::ChunkItems< Entity::Generator::Generator >::ItemRefCollection
using ModulatorCollection = IO::ChunkItems< Entity::Modulator::Modulator >::ItemRefCollection
Static Public Attributes inherited from SF2::Render::Zone
static MIDIRange const all = MIDIRange(0, 255)
A range that always returns true for any MIDI value.
Protected Member Functions inherited from SF2::Render::Zone
Zone (GeneratorCollection &&gens, ModulatorCollection &&mods, Entity::Generator::Index terminal)
Constructor.
uint16_t resourceLink () const
Obtain the link to the resource used by this zone.
void apply (Voice::State &state) const
Apply the instrument zone to the given voice state.
void refine (Voice::State &state) const
Apply the zone to the given voice state by adjusting the value using the generator in the zone.
Detailed Description
A specialization of a Zone for an Instrument.
Instrument zones have a sample buffer.
Constructor & Destructor Documentation
InstrumentZone()
SF2::Render::InstrumentZone::InstrumentZone (const IO::File & file, const Entity::Bag & bag) inline
Construct new zone from entity in file.
Parameters
file the file to work with
bag the zone definition
Member Function Documentation
apply()
void SF2::Render::InstrumentZone::apply (Voice::State & state) const inline
Apply the zone generator values to the given voice state.
Parameters
state the state to update
References SF2::Render::Zone::apply().
Referenced by SF2::Render::Voice::Setup::apply().
sampleBuffer()
const Render::Sample::CanonicalBuffer* SF2::Render::InstrumentZone::sampleBuffer () const inline
Returns
the sample buffer registered to this zone, or nullptr if this is a global zone.
Referenced by SF2::Render::Voice::Setup::sampleBuffer().
The documentation for this class was generated from the following file:
SoundFontInfoLib/Render/InstrumentZone.hpp