SoundFontInfoLib: SF2::Render::InputBuffer Struct Reference
SF2::Render::InputBuffer Struct Reference
Maintains a buffer of PCM samples which is used to save samples from an upstream node.
#include <InputBuffer.hpp>
Public Member Functions
void allocateBuffers (AVAudioFormat *format, AUAudioFrameCount maxFrames)
Set the format of the buffer to use.
void releaseBuffers ()
Forget any allocated buffers.
AUAudioUnitStatus pullInput (AudioUnitRenderActionFlags *actionFlags, AudioTimeStamp const *timestamp, AVAudioFrameCount frameCount, NSInteger inputBusNumber, AURenderPullInputBlock pullInputBlock)
Obtain samples from an upstream node.
void prepareBufferList (AVAudioFrameCount frameCount)
Update the input buffer to reflect current format.
AudioBufferList * mutableAudioBufferList () const
Obtain a pointer to a mutable version of the internal channel buffers.
BufferFacet & bufferFacet ()
Obtain the BufferFacet that manages the held AudioBufferList and provides a std::vector view of them.
size_t channelCount () const
Obtain the number of input channels.
AUValue * operator[] (size_t index) const
Obtain the channel buffer.
Detailed Description
Maintains a buffer of PCM samples which is used to save samples from an upstream node.
Note that despite its name, there are multiple sample buffers held within, one for each channel of input.
Member Function Documentation
allocateBuffers()
void SF2::Render::InputBuffer::allocateBuffers (AVAudioFormat * format, AUAudioFrameCount maxFrames) inline
Set the format of the buffer to use.
Parameters
format the format of the samples
maxFrames the maximum number of frames to be found in the upstream output
References SF2::Render::BufferFacet::setBufferList().
bufferFacet()
BufferFacet& SF2::Render::InputBuffer::bufferFacet () inline
Obtain the BufferFacet that manages the held AudioBufferList and provides a std::vector view of them.
channelCount()
size_t SF2::Render::InputBuffer::channelCount () const inline
Obtain the number of input channels.
Returns
channel count
References SF2::Render::BufferFacet::channelCount().
mutableAudioBufferList()
AudioBufferList* SF2::Render::InputBuffer::mutableAudioBufferList () const inline
Obtain a pointer to a mutable version of the internal channel buffers.
Returns
AudioBufferList pointer.
operator[]()
AUValue* SF2::Render::InputBuffer::operator[] (size_t index) const inline
Obtain the channel buffer.
Returns
writable pointer to a channel buffer
prepareBufferList()
void SF2::Render::InputBuffer::prepareBufferList (AVAudioFrameCount frameCount) inline
Update the input buffer to reflect current format.
Parameters
frameCount the number of frames to expect to place in the buffer
Referenced by pullInput().
pullInput()
AUAudioUnitStatus SF2::Render::InputBuffer::pullInput (AudioUnitRenderActionFlags * actionFlags, AudioTimeStamp const * timestamp, AVAudioFrameCount frameCount, NSInteger inputBusNumber, AURenderPullInputBlock pullInputBlock) inline
Obtain samples from an upstream node.
Output is stored in internal buffer.
Parameters
actionFlags render flags from the host
timestamp the current transport time of the samples
frameCount the number of frames to process
inputBusNumber the bus to pull from
pullInputBlock the function to call to do the pulling
References prepareBufferList().
releaseBuffers()
void SF2::Render::InputBuffer::releaseBuffers () inline
Forget any allocated buffers.
References SF2::Render::BufferFacet::release().
The documentation for this struct was generated from the following file:
SoundFontInfoLib/Render/InputBuffer.hpp