disabled_rules: # rule identifiers to exclude from running
  - statement_position
  - todo
  - nesting

opt_in_rules: # some rules are only opt-in
  - empty_count

included: # paths to include during linting. `--path` is ignored if present.
  - App
  - SoundFontsFramework
  - SoundFontInfoLib

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - SoundFontsFramework/Keyboard View/KeyboardRender.swift

# binary rules can set their severity level
force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

# Xcode guidepost at 120 but do not warn until 140 and error at 240
line_length:
  warning: 140
  error: 240
  ignores_comments: true
  ignores_urls: true

# or they can set both explicitly
file_length:
  warning: 1000
  error: 2000

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: 2 # only warning

  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
