disabled_rules: # rule identifiers to exclude from running
  - statement_position

opt_in_rules: # some rules are only opt-in
  - empty_count

included: # paths to include during linting. `--path` is ignored if present.
  - App

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - App/Keyboard/KeyboardRender.swift

# binary rules can set their severity level
force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
# line_length: 110

# or they can set both explicitly
file_length:
  warning: 500
  error: 600

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: 2 # only warning

  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
