SoundFontInfoLib: SF2::Entity::Generator::Amount Class Reference
SF2::Entity::Generator::Amount Class Reference
Holds the amount to apply to a generator.
#include <Amount.hpp>
Public Member Functions
Amount (uint16_t raw)
Constructor with specific value.
Amount ()
Default constructor.
uint16_t unsignedAmount () const
int16_t signedAmount () const
short low () const
short high () const
Static Public Attributes
static constexpr size_t size = 2
Detailed Description
Holds the amount to apply to a generator.
Note that this is an immutable value that comes straight from an SF2 file. It exists as a C union of three value types: unsigned 16-bit int, signed 16-bit int, and pair of 2 unsigned 8-bit values used for MIDI key/velocity ranges. As such, it is important to pull out the right value with the right method. The associated Definition metadata class has methods that can be used to do this correctly and safely.
Constructor & Destructor Documentation
Amount() [1/2]
SF2::Entity::Generator::Amount::Amount (uint16_t raw) inline explicit
Constructor with specific value.
Only used for testing. All values for generators should come from SF2 file.
Parameters
raw the value to hold
References size.
Amount() [2/2]
SF2::Entity::Generator::Amount::Amount () inline
Default constructor.
Sets held value to 0.
Member Function Documentation
high()
short SF2::Entity::Generator::Amount::high () const inline
Returns
high value of a range (0-255)
Referenced by SF2::Entity::Generator::Definition::dump().
low()
short SF2::Entity::Generator::Amount::low () const inline
Returns
low value of a range (0-255)
Referenced by SF2::Entity::Generator::Definition::dump().
signedAmount()
int16_t SF2::Entity::Generator::Amount::signedAmount () const inline
Returns
signed integer value
Referenced by SF2::Entity::Generator::Definition::dump(), and SF2::Entity::Generator::Definition::valueOf().
unsignedAmount()
uint16_t SF2::Entity::Generator::Amount::unsignedAmount () const inline
Returns
unsigned integer value
Referenced by SF2::Entity::Generator::Definition::dump(), and SF2::Entity::Generator::Definition::valueOf().
Member Data Documentation
ranges
uint8_t SF2::Entity::Generator::Amount::ranges[2]
shAmount
int16_t SF2::Entity::Generator::Amount::shAmount
size
constexpr size_t SF2::Entity::Generator::Amount::size = 2 static constexpr
Referenced by Amount().
wAmount
uint16_t SF2::Entity::Generator::Amount::wAmount
The documentation for this class was generated from the following file:
SoundFontInfoLib/Entity/Generator/Amount.hpp