# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 12 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (4th generation)"
])

languages([
  "en-US"
])

clear_previous_screenshots(true)
concurrent_simulators(false)
