# Uncomment the lines below you want to change by removing the # in the beginning
workspace("/Users/howes/src/SoundFonts/SoundFonts.xcworkspace")

# A list of devices you want to take the screenshots from
devices([
    "iPhone 6s",
    "iPhone SE",
    "iPhone Xʀ",
    "iPhone 11",
    "iPhone 11 Pro Max",
    "iPad Pro (12.9-inch) (2nd generation)",
    "iPad Pro (12.9-inch) (3rd generation)",
    "iPad Mini"
])

languages([
  "en-US"
])

concurrent_simulators(false)

# The name of the scheme which contains the UI Tests
scheme("ScreenShots")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["--screenshots"])

stop_after_first_error(true)

# For more information about all available options run
# fastlane action snapshot
