SoundFontInfoLib: SF2::Entity::Generator::Generator Class Reference
SF2::Entity::Generator::Generator Class Reference
Memory layout of a 'pgen'/'igen' entry.
#include <Generator.hpp>
Public Member Functions
Generator (IO::Pos &pos)
Constructor from file.
Index index () const
Amount amount () const
const Definition & definition () const
const std::string & name () const
int value () const
void dump (const std::string &indent, int index) const
Static Public Attributes
static constexpr size_t size = 4
Detailed Description
Memory layout of a 'pgen'/'igen' entry.
The size of this is defined to be 4. Each instance represents a generator configuration.
Constructor & Destructor Documentation
Generator()
SF2::Entity::Generator::Generator::Generator (IO::Pos & pos) inline explicit
Constructor from file.
Parameters
pos location in file to read
References SF2::IO::Pos::readInto(), and size.
Member Function Documentation
amount()
Amount SF2::Entity::Generator::Generator::amount () const inline
Returns
value configured for the generator
definition()
const Definition& SF2::Entity::Generator::Generator::definition () const inline
Returns
meta-data for the generator
References SF2::Entity::Generator::Definition::definition(), and SF2::Entity::Generator::RawIndex::index().
Referenced by dump(), name(), and value().
dump()
void Generator::dump (const std::string & indent, int index) const
References definition(), index(), and name().
index()
Index SF2::Entity::Generator::Generator::index () const inline
Returns
index of the generator as an enumerated type
References SF2::Entity::Generator::RawIndex::index().
Referenced by dump().
name()
const std::string& SF2::Entity::Generator::Generator::name () const inline
Returns
the name of the generator
References definition(), and SF2::Entity::Generator::Definition::name().
Referenced by dump().
value()
int SF2::Entity::Generator::Generator::value () const inline
Returns
the configured value of a generator
References definition(), and SF2::Entity::Generator::Definition::valueOf().
Member Data Documentation
size
constexpr size_t SF2::Entity::Generator::Generator::size = 4 static constexpr
Referenced by Generator().
The documentation for this class was generated from the following files:
SoundFontInfoLib/SoundFontInfoLib/Entity/Generator/Generator.hpp
SoundFontInfoLib/SoundFontInfoLib/Entity/Generator/Generator.cpp