SoundFontInfoLib: SF2::IO::Parser Class Reference
SF2::IO::Parser Class Reference
SoundFont file parser.
#include <Parser.hpp>
Classes
struct Info
Extract SF2 info.
struct PresetInfo
Extracted preset information from the SF2 file.
Static Public Member Functions
static Info parse (int fd, size_t size)
Attempt to parse a SoundFont resource.
Detailed Description
SoundFont file parser.
Member Function Documentation
parse()
Parser::Info Parser::parse (int fd, size_t size) static
Attempt to parse a SoundFont resource.
Any failures to do so will throw a FormatError exception. Note that this really just parses any RIFF format. We postpone the SF2 evaluation until the initial loading is done.
parameter fd: file descriptor of the SF2 file to read from for data
parameter size: the number of bytes available for processing
References SF2::Entity::Preset::bank(), SF2::IO::error, SF2::IO::icmt, SF2::IO::icop, SF2::IO::ieng, SF2::IO::inam, SF2::IO::info, SF2::IO::Pos::makeChunkList(), SF2::Entity::Preset::name(), SF2::IO::phdr, SF2::Entity::Preset::preset(), SF2::IO::riff, and SF2::IO::sfbk.
The documentation for this class was generated from the following files:
SoundFontInfoLib/SoundFontInfoLib/IO/Parser.hpp
SoundFontInfoLib/SoundFontInfoLib/IO/Parser.cpp