SoundFontInfoLib: SF2::Render::Envelope::Stage Class Reference
SF2::Render::Envelope::Stage Class Reference
Configuration for a single stage of an envelope.
#include <Stage.hpp>
Public Member Functions
double next (double last) const
Obtain the next value of a stage.
Static Public Member Functions
static Stage SetConstant (StageIndex stageIndex, int sampleCount, double value)
Generate a configuration that will emit a constant value for a fixed or indefinite time.
static Stage ConfigureDelay (int sampleCount)
Generate a configuration for the delay stage.
static Stage ConfigureAttack (int sampleCount, double curvature)
Generate a configuration for the attack stage.
static Stage ConfigureHold (int sampleCount)
Generate a configuration for the delay stage.
static Stage ConfigureDecay (int sampleCount, double curvature, double sustainLevel)
Generate a configuration for the decay stage.
static Stage ConfigureSustain (double level)
Generate a configuration for the sustain stage.
static Stage ConfigureRelease (int sampleCount, double curvature, double sustainLevel)
Generate a configuration for the release stage.
Static Public Attributes
static constexpr double minimumCurvature = 0.000000001
static constexpr double maximumCurvature = 10.0
Friends
class Generator
Detailed Description
Configuration for a single stage of an envelope.
Member Function Documentation
ConfigureAttack()
static Stage SF2::Render::Envelope::Stage::ConfigureAttack (int sampleCount, double curvature) inline static
Generate a configuration for the attack stage.
References SF2::Render::Envelope::attack.
ConfigureDecay()
static Stage SF2::Render::Envelope::Stage::ConfigureDecay (int sampleCount, double curvature, double sustainLevel) inline static
Generate a configuration for the decay stage.
References SF2::Render::Envelope::decay.
ConfigureDelay()
static Stage SF2::Render::Envelope::Stage::ConfigureDelay (int sampleCount) inline static
Generate a configuration for the delay stage.
References SF2::Render::Envelope::delay, and SetConstant().
ConfigureHold()
static Stage SF2::Render::Envelope::Stage::ConfigureHold (int sampleCount) inline static
Generate a configuration for the delay stage.
References SF2::Render::Envelope::hold, and SetConstant().
ConfigureRelease()
static Stage SF2::Render::Envelope::Stage::ConfigureRelease (int sampleCount, double curvature, double sustainLevel) inline static
Generate a configuration for the release stage.
References SF2::Render::Envelope::release.
ConfigureSustain()
static Stage SF2::Render::Envelope::Stage::ConfigureSustain (double level) inline static
Generate a configuration for the sustain stage.
References SetConstant(), and SF2::Render::Envelope::sustain.
next()
double SF2::Render::Envelope::Stage::next (double last) const inline
Obtain the next value of a stage.
Parameters
last last value generated by a stage
Returns
new value
SetConstant()
static Stage SF2::Render::Envelope::Stage::SetConstant (StageIndex stageIndex, int sampleCount, double value) inline static
Generate a configuration that will emit a constant value for a fixed or indefinite time.
Referenced by ConfigureDelay(), ConfigureHold(), and ConfigureSustain().
Friends And Related Function Documentation
Generator
friend class Generator friend
Member Data Documentation
maximumCurvature
constexpr double SF2::Render::Envelope::Stage::maximumCurvature = 10.0 inline static constexpr
minimumCurvature
constexpr double SF2::Render::Envelope::Stage::minimumCurvature = 0.000000001 inline static constexpr
The documentation for this class was generated from the following file:
SoundFontInfoLib/SoundFontInfoLib/Render/Envelope/Stage.hpp