SoundFontInfoLib: SF2::Render::Voice::Voice Class Reference
SF2::Render::Voice::Voice Class Reference
A voice renders audio samples for a given note / pitch.
#include <Voice.hpp>
Public Member Functions
Voice (double sampleRate, const MIDI::Channel &channel, const Setup &setup)
Construct a new voice renderer.
void keyReleased ()
Signal the envelopes that the key is no longer pressed, transitioning to release phase.
bool isActive () const
bool canLoop () const
double render ()
Detailed Description
A voice renders audio samples for a given note / pitch.
Constructor & Destructor Documentation
Voice()
Voice::Voice (double sampleRate, const MIDI::Channel & channel, const Setup & setup)
Construct a new voice renderer.
Parameters
sampleRate the sample rate to use for generating audio
channel the MIDI state associated with the renderer
setup the zones to apply to build the generator state
References SF2::Entity::Generator::delayModulatorLFO, SF2::Entity::Generator::delayVibratoLFO, SF2::Entity::Generator::frequencyModulatorLFO, and SF2::Entity::Generator::frequencyVibratoLFO.
Member Function Documentation
canLoop()
bool SF2::Render::Voice::Voice::canLoop () const inline
Returns
true if the voice can enter a loop if it is available
References SF2::Render::Voice::State::continuously, SF2::Render::Voice::State::duringKeyPress, and SF2::Render::Envelope::Generator::isGated().
Referenced by render().
isActive()
bool SF2::Render::Voice::Voice::isActive () const inline
Returns
true if this voice is still rendering interesting samples
References SF2::Render::Envelope::Generator::isActive().
Referenced by render().
keyReleased()
void SF2::Render::Voice::Voice::keyReleased () inline
Signal the envelopes that the key is no longer pressed, transitioning to release phase.
References SF2::Render::Envelope::Generator::gate().
render()
double SF2::Render::Voice::Voice::render () inline
Returns
renders a sample
References canLoop(), SF2::Render::Sample::Generator::generate(), isActive(), SF2::Render::Voice::State::modulated(), SF2::Entity::Generator::modulatorEnvelopeToPitch, SF2::Entity::Generator::modulatorLFOToPitch, SF2::Render::Envelope::Generator::process(), SF2::Render::LFO::valueAndIncrement(), and SF2::Entity::Generator::vibratoLFOToPitch.
The documentation for this class was generated from the following files:
SoundFontInfoLib/SoundFontInfoLib/Render/Voice/Voice.hpp
SoundFontInfoLib/SoundFontInfoLib/Render/Voice/Voice.cpp