SoundFontInfoLib: SF2::Render::Envelope::Generator Class Reference
SF2::Render::Envelope::Generator Class Reference
Generator of values for the SF2 volume/filter envelopes.
#include <Generator.hpp>
Public Types
using Index = Entity::Generator::Index
Public Member Functions
Generator (double sampleRate)
Create new envelope definition with a bare configuration.
Generator (double sampleRate, double delay, double attack, double hold, double decay, double sustain, double release, bool noteOn=false)
Create new envelope definition.
void gate (bool noteOn)
Set the status of a note playing.
StageIndex stage () const
bool isActive () const
bool isGated () const
double value () const
double process ()
Calculate the next envelope value.
Static Public Member Functions
static Generator Volume (const Voice::State &state)
Create new envelope for gain amp.
static Generator Modulator (const Voice::State &state)
Create new envelope for modulation.
Static Public Attributes
static constexpr double defaultCurvature = 0.01
Detailed Description
Generator of values for the SF2 volume/filter envelopes.
An envelope contains 6 stages:
Delay – number of seconds to delay the beginning of the attack stage
Attack – number of seconds to ramp up from 0.0 to 1.0. Also supports non-linear curvature.
Hold – number of seconds to hold the envelope at 1.0 before entering the decay stage.
Decay – number of seconds to lower the envelope from 1.0 to the sustain level
Sustain – a stage that lasts as long as a note is held down
Release – number of seconds to go from sustain level to 0.0
The envelope will remain in the idle state until gate(true) is invoked. It will remain in the sustain stage until gate(false) is invoked at which point it will enter the release stage. Although the stages above are listed in the order in which they are performed, any stage will transition to the release stage upon a gate(false) call.
The more traditional ADSR (attack, decay, sustain, release) envelope can be achieve by setting the delay and hold durations to zero (0.0).
Member Typedef Documentation
Index
using SF2::Render::Envelope::Generator::Index = Entity::Generator::Index
Constructor & Destructor Documentation
Generator() [1/2]
SF2::Render::Envelope::Generator::Generator (double sampleRate) inline explicit
Create new envelope definition with a bare configuration.
Parameters
sampleRate number of samples per second
Referenced by Modulator(), and Volume().
Generator() [2/2]
SF2::Render::Envelope::Generator::Generator (double sampleRate, double delay, double attack, double hold, double decay, double sustain, double release, bool noteOn = false) inline
Create new envelope definition.
Parameters
sampleRate number of samples per second
delay number of seconds before the attack stage begins
attack duration of the attack stage where the envelope ramps from 0.0 to 1.0
hold duration of the hold stage where the envelope remains at 1.0
decay duration of the decay stage where the envelope ramps down from 1.0 to the sustain level
sustain the sustain level (between 0.0 and 1.0)
release duration of the release stage where the envelope ramps down from the sustain level to 0.0
noteOn if true, start the envelope
References SF2::Render::Envelope::attack, SF2::Render::Envelope::decay, SF2::Render::Envelope::delay, gate(), SF2::Render::Envelope::hold, SF2::Render::Envelope::release, and SF2::Render::Envelope::sustain.
Member Function Documentation
gate()
void SF2::Render::Envelope::Generator::gate (bool noteOn) inline
Set the status of a note playing.
When true, the envelope begins proper. When set to false, the envelope will jump to the release stage.
References SF2::Render::Envelope::delay, SF2::Render::Envelope::idle, and SF2::Render::Envelope::release.
Referenced by Generator(), and SF2::Render::Voice::Voice::keyReleased().
isActive()
bool SF2::Render::Envelope::Generator::isActive () const inline
Returns
true if the generator still has values to emit
References SF2::Render::Envelope::idle.
Referenced by SF2::Render::Voice::Voice::isActive(), and isGated().
isGated()
bool SF2::Render::Envelope::Generator::isGated () const inline
Returns
true if the generator is active and has not yet reached the release state
References isActive(), and SF2::Render::Envelope::release.
Referenced by SF2::Render::Voice::Voice::canLoop().
Modulator()
static Generator SF2::Render::Envelope::Generator::Modulator (const Voice::State & state) inline static
Create new envelope for modulation.
Parameters
state the state holding the generator values for the envelope definition
References SF2::DSP::centsToSeconds(), Generator(), SF2::Render::Voice::State::keyedModulatorEnvelopeDecay(), SF2::Render::Voice::State::keyedModulatorEnvelopeHold(), SF2::Render::Voice::State::modulated(), SF2::Render::Voice::State::sampleRate(), and SF2::Render::Voice::State::sustainLevelModulatorEnvelope().
process()
double SF2::Render::Envelope::Generator::process () inline
Calculate the next envelope value.
This must be called on every sample for proper timing of the stages.
Returns
the new envelope value.
References SF2::Render::Envelope::attack, SF2::Render::Envelope::decay, SF2::Render::Envelope::delay, SF2::Render::Envelope::hold, SF2::Render::Envelope::idle, SF2::Render::Envelope::release, and SF2::Render::Envelope::sustain.
Referenced by SF2::Render::Voice::Voice::render().
stage()
StageIndex SF2::Render::Envelope::Generator::stage () const inline
Returns
the currently active stage.
value()
double SF2::Render::Envelope::Generator::value () const inline
Returns
the current envelope value.
Volume()
static Generator SF2::Render::Envelope::Generator::Volume (const Voice::State & state) inline static
Create new envelope for gain amp.
Parameters
state the state holding the generator values for the envelope definition
References SF2::DSP::centsToSeconds(), Generator(), SF2::Render::Voice::State::keyedVolumeEnvelopeDecay(), SF2::Render::Voice::State::keyedVolumeEnvelopeHold(), SF2::Render::Voice::State::modulated(), SF2::Render::Voice::State::sampleRate(), and SF2::Render::Voice::State::sustainLevelVolumeEnvelope().
Member Data Documentation
defaultCurvature
constexpr double SF2::Render::Envelope::Generator::defaultCurvature = 0.01 inline static constexpr
The documentation for this class was generated from the following file:
SoundFontInfoLib/SoundFontInfoLib/Render/Envelope/Generator.hpp