SoundFontInfoLib: SF2::Entity::Modulator::Source Class Reference
SF2::Entity::Modulator::Source Class Reference
The source of an SF2 modulator.
#include <Source.hpp>
Public Types
enum class GeneralIndex : uint16_t {
none = 0 , noteOnVelocity = 2 , noteOnKeyValue = 3 , polyPressure = 10 ,
channelPressure = 13 , pitchWheel = 14 , pitchWheelSensitivity = 16 , link = 127
}
Valid sources for a general controller.
enum class ContinuityType : uint16_t { linear = 0 , concave , convex , switched }
Transformations applied to values that come from a source.
Public Member Functions
Source (uint16_t bits)
Constructor.
Source ()=default
bool isValid () const
bool isContinuousController () const
bool isGeneralController () const
bool isUnipolar () const
bool isBipolar () const
bool isMinToMax () const
bool isMaxToMin () const
bool isLinked () const
GeneralIndex generalIndex () const
bool isNone () const
int continuousIndex () const
ContinuityType type () const
std::string continuityTypeName () const
std::string description () const
bool operator== (const Source &rhs) const
bool operator!= (const Source &rhs) const
Friends
std::ostream & operator<< (std::ostream &os, const Source &mod)
Detailed Description
The source of an SF2 modulator.
There are two types:
general controller
MIDI continuous controller (CC)
The type is defined by the CC flag (bit 7). The general type points to various common MIDI values as a source of modulation, while the CC type allows for a broader collection of controllers.
Member Enumeration Documentation
ContinuityType
enum SF2::Entity::Modulator::Source::ContinuityType : uint16_t strong
Transformations applied to values that come from a source.
Enumerator
linear
concave
convex
switched
GeneralIndex
enum SF2::Entity::Modulator::Source::GeneralIndex : uint16_t strong
Valid sources for a general controller.
Enumerator
none
noteOnVelocity
noteOnKeyValue
polyPressure
channelPressure
pitchWheel
pitchWheelSensitivity
link
Constructor & Destructor Documentation
Source() [1/2]
SF2::Entity::Modulator::Source::Source (uint16_t bits) inline explicit
Constructor.
Parameters
bits value that defines a source
Source() [2/2]
SF2::Entity::Modulator::Source::Source () default
Member Function Documentation
continuityTypeName()
std::string SF2::Entity::Modulator::Source::continuityTypeName () const inline
Returns
the name of the continuity type
References isValid().
Referenced by description().
continuousIndex()
int SF2::Entity::Modulator::Source::continuousIndex () const inline
Returns
the index of the continuous controller (raises exception if not configured to be a continuous controller)
References isContinuousController(), and isValid().
Referenced by description().
description()
std::string Source::description () const
References channelPressure, continuityTypeName(), continuousIndex(), generalIndex(), isContinuousController(), isGeneralController(), isMinToMax(), isUnipolar(), link, none, noteOnKeyValue, noteOnVelocity, pitchWheel, pitchWheelSensitivity, and polyPressure.
generalIndex()
GeneralIndex SF2::Entity::Modulator::Source::generalIndex () const inline
Returns
the index of the general controller (raises exception if not configured to be a general controller)
References isGeneralController(), and isValid().
Referenced by description(), isLinked(), and isNone().
isBipolar()
bool SF2::Entity::Modulator::Source::isBipolar () const inline
Returns
true if the source acts in a bipolar manner
References isUnipolar().
isContinuousController()
bool SF2::Entity::Modulator::Source::isContinuousController () const inline
Returns
true if the source is a continuous controller (CC)
Referenced by continuousIndex(), description(), isGeneralController(), and isValid().
isGeneralController()
bool SF2::Entity::Modulator::Source::isGeneralController () const inline
Returns
true if the source is a general controller
References isContinuousController().
Referenced by description(), generalIndex(), isLinked(), and isNone().
isLinked()
bool SF2::Entity::Modulator::Source::isLinked () const inline
Returns
true if this modulator relies on another for a source value
References generalIndex(), isGeneralController(), isValid(), and link.
isMaxToMin()
bool SF2::Entity::Modulator::Source::isMaxToMin () const inline
Returns
true if the source values go from large to small as the controller goes from min to max
References isMinToMax().
isMinToMax()
bool SF2::Entity::Modulator::Source::isMinToMax () const inline
Returns
true if the source values go from small to large as the controller goes from min to max
Referenced by description(), and isMaxToMin().
isNone()
bool SF2::Entity::Modulator::Source::isNone () const inline
Returns
true if this source is not connected to anything (or it is invalid)
References generalIndex(), isGeneralController(), isValid(), and none.
isUnipolar()
bool SF2::Entity::Modulator::Source::isUnipolar () const inline
Returns
true if the source acts in a unipolar manner
Referenced by description(), and isBipolar().
isValid()
bool SF2::Entity::Modulator::Source::isValid () const inline
Returns
true if the source is valid
References isContinuousController(), and switched.
Referenced by continuityTypeName(), continuousIndex(), generalIndex(), isLinked(), isNone(), and type().
operator!=()
bool SF2::Entity::Modulator::Source::operator!= (const Source & rhs) const inline
operator==()
bool SF2::Entity::Modulator::Source::operator== (const Source & rhs) const inline
type()
ContinuityType SF2::Entity::Modulator::Source::type () const inline
Returns
the continuity type for the controller values
References isValid().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Source & mod) friend
The documentation for this class was generated from the following files:
SoundFontInfoLib/SoundFontInfoLib/Entity/Modulator/Source.hpp
SoundFontInfoLib/SoundFontInfoLib/Entity/Modulator/Source.cpp