SoundFontInfoLib: SF2::Entity::Modulator::Modulator Class Reference
SF2::Entity::Modulator::Modulator Class Reference
Memory layout of a 'pmod'/'imod' entry.
#include <Modulator.hpp>
Public Member Functions
Modulator (IO::Pos &pos)
Construct instance from contents of SF2 file.
Modulator (Source modSrcOper, Generator::Index dest, int16_t amount, Source modAmtSrcOper, Transform transform)
Construct instance from values.
const Source & source () const
bool hasModulatorDestination () const
bool hasGeneratorDestination () const
Generator::Index generatorDestination () const
size_t linkDestination () const
int16_t amount () const
const Source & amountSource () const
Transform transform () const
std::string description () const
bool operator== (const Modulator &rhs) const
bool operator!= (const Modulator &rhs) const
void dump (const std::string &indent, int index) const
Static Public Attributes
static constexpr size_t size = 10
static std::array< Modulator, size > const defaults
Detailed Description
Memory layout of a 'pmod'/'imod' entry.
The size of this is defined to be 10.
Defines a mapping of a modulator to a generator so that a modulator can affect the value given by a generator. Per the spec a modulator can have two sources. If the first one is 'none', then the modulator will always return 0.0. The second one is optional – if it exists then it will scale the result of the previous source value. Otherwise, it just acts as if the source returned 1.0.
Per the spec, modulators are unique if they do not share the same sfModSrcOper, sfModDestOper, sfModAmtSrcOper values. If there are duplicates, the second occurrence wins.
Constructor & Destructor Documentation
Modulator() [1/2]
SF2::Entity::Modulator::Modulator::Modulator (IO::Pos & pos) inline explicit
Construct instance from contents of SF2 file.
Parameters
pos location to read from
References SF2::IO::Pos::readInto(), and size.
Modulator() [2/2]
SF2::Entity::Modulator::Modulator::Modulator (Source modSrcOper, Generator::Index dest, int16_t amount, Source modAmtSrcOper, Transform transform) inline
Construct instance from values.
Used to define default mods and support unit tests.
Member Function Documentation
amount()
int16_t SF2::Entity::Modulator::Modulator::amount () const inline
Returns
the maximum deviation that a modulator can apply to a generator
amountSource()
const Source& SF2::Entity::Modulator::Modulator::amountSource () const inline
Returns
the second source of data for the modulator
description()
std::string Modulator::description () const
References SF2::Entity::Generator::Definition::definition(), generatorDestination(), hasModulatorDestination(), linkDestination(), SF2::Entity::Generator::Definition::name(), and transform().
Referenced by SF2::Render::Modulator::description(), dump(), and SF2::Render::Modulator::Modulator().
dump()
void Modulator::dump (const std::string & indent, int index) const
References description().
generatorDestination()
Generator::Index SF2::Entity::Modulator::Modulator::generatorDestination () const inline
Returns
the destination (generator) for the modulator
References hasGeneratorDestination().
Referenced by SF2::Render::Voice::State::addModulator(), and description().
hasGeneratorDestination()
bool SF2::Entity::Modulator::Modulator::hasGeneratorDestination () const inline
Returns
true if this modulator directly affects a generator value
References hasModulatorDestination().
Referenced by SF2::Render::Voice::State::addModulator(), and generatorDestination().
hasModulatorDestination()
bool SF2::Entity::Modulator::Modulator::hasModulatorDestination () const inline
Returns
true if this modulator is the source of a value for another modulator
Referenced by description(), hasGeneratorDestination(), and linkDestination().
linkDestination()
size_t SF2::Entity::Modulator::Modulator::linkDestination () const inline
Returns
the destination modulator
References hasModulatorDestination().
Referenced by description().
operator!=()
bool SF2::Entity::Modulator::Modulator::operator!= (const Modulator & rhs) const inline
References operator==().
operator==()
bool SF2::Entity::Modulator::Modulator::operator== (const Modulator & rhs) const inline
Referenced by operator!=().
source()
const Source& SF2::Entity::Modulator::Modulator::source () const inline
Returns
the source of data for the modulator
transform()
Transform SF2::Entity::Modulator::Modulator::transform () const inline
Returns
the transform to apply to values created by the modulator
Referenced by description().
Member Data Documentation
defaults
std::array< Modulator, Modulator::size > const Modulator::defaults static
Initial value:
{
    Modulator(Source(0x0502), Generator::Index::initialAttenuation, 960, Source(0), Transform(0)),
    Modulator(Source(0x0102), Generator::Index::initialFilterCutoff, -2400, Source(0), Transform(0)),
    Modulator(Source(0x000D), Generator::Index::vibratoLFOToPitch, 50, Source(0), Transform(0)),
    Modulator(Source(0x0081), Generator::Index::vibratoLFOToPitch, 50, Source(0), Transform(0)),
    Modulator(Source(0x0587), Generator::Index::initialAttenuation, 960, Source(0), Transform(0)),
    Modulator(Source(0x028A), Generator::Index::pan, 1000, Source(0), Transform(0)),
    Modulator(Source(0x058B), Generator::Index::initialAttenuation, 960, Source(0), Transform(0)),
    Modulator(Source(0x00DB), Generator::Index::reverbEffectSend, 200, Source(0), Transform(0)),
    Modulator(Source(0x00DD), Generator::Index::chorusEffectSend, 200, Source(0), Transform(0)),
    Modulator(Source(0x020E), Generator::Index::initialPitch, 12700, Source(0x0010), Transform(0))
}
size
constexpr size_t SF2::Entity::Modulator::Modulator::size = 10 static constexpr
Referenced by Modulator().
The documentation for this class was generated from the following files:
SoundFontInfoLib/SoundFontInfoLib/Entity/Modulator/Modulator.hpp
SoundFontInfoLib/SoundFontInfoLib/Entity/Modulator/Modulator.cpp