SoundFontInfoLib: SF2::Render::DelayBuffer< T > Class Template Reference
SF2::Render::DelayBuffer< T > Class Template Reference
Circular buffer that acts as a delay for samples.
#include <DelayBuffer.hpp>
Public Member Functions
DelayBuffer (double sizeInSamples)
Construct new buffer.
void clear ()
Clear the buffer by setting all entries to zero.
void setSizeInSamples (double sizeInSamples)
Resize the buffer.
void write (T value)
Place a sample in the buffer, overwriting the oldest.
size_t size () const
Obtain the size of the buffer.
T readFromOffset (int offset) const
Read the value at the given offset from the newest value.
T read (double delay) const
Read the value at the given offset from the newest value.
Detailed Description
template<typename T>
class SF2::Render::DelayBuffer< T >
Circular buffer that acts as a delay for samples.
Constructor & Destructor Documentation
DelayBuffer()
template<typename T > SF2::Render::DelayBuffer< T >::DelayBuffer (double sizeInSamples) inline
Construct new buffer.
Parameters
sizeInSamples number of samples to hold in the buffer
References SF2::Render::DelayBuffer< T >::clear().
Member Function Documentation
clear()
template<typename T > void SF2::Render::DelayBuffer< T >::clear () inline
Clear the buffer by setting all entries to zero.
Referenced by SF2::Render::DelayBuffer< T >::DelayBuffer(), and SF2::Render::DelayBuffer< T >::setSizeInSamples().
read()
template<typename T > T SF2::Render::DelayBuffer< T >::read (double delay) const inline
Read the value at the given offset from the newest value.
Parameters
delay the offset from the most recently written sample
Returns
the value from the buffer
References SF2::Render::DelayBuffer< T >::readFromOffset().
readFromOffset()
template<typename T > T SF2::Render::DelayBuffer< T >::readFromOffset (int offset) const inline
Read the value at the given offset from the newest value.
Parameters
offset the offset from the most recently written sample
Returns
the value from the buffer
Referenced by SF2::Render::DelayBuffer< T >::read().
setSizeInSamples()
template<typename T > void SF2::Render::DelayBuffer< T >::setSizeInSamples (double sizeInSamples) inline
Resize the buffer.
Parameters
sizeInSamples new number of samples to hold
References SF2::Render::DelayBuffer< T >::clear().
size()
template<typename T > size_t SF2::Render::DelayBuffer< T >::size () const inline
Obtain the size of the buffer.
Returns
buffer size
write()
template<typename T > void SF2::Render::DelayBuffer< T >::write (T value) inline
Place a sample in the buffer, overwriting the oldest.
Parameters
value the value to write
The documentation for this class was generated from the following file:
SoundFontInfoLib/SoundFontInfoLib/Render/DelayBuffer.hpp