SoundFontInfoLib: SF2::Render::Sample::Generator Class Reference
SF2::Render::Sample::Generator Class Reference
Generator of new samples from a stream of original samples, properly scaled to sound correct for the output sample rate and the desired output frequency.
#include <Generator.hpp>
Public Types
enum class Interpolator { linear , cubic4thOrder }
Public Member Functions
Generator (const CanonicalBuffer &samples, const Voice::State &state, Interpolator kind=Interpolator::linear)
Construct a new sample generator.
double generate (double pitchAdjustment, bool canLoop)
Obtain an interpolated sample value at the given index.
Detailed Description
Generator of new samples from a stream of original samples, properly scaled to sound correct for the output sample rate and the desired output frequency.
We know the original samples' sample rate and root frequency, so we can do some simple math to calculate a proper increment to use when iterating through the original samples, and with some proper interpolation we should end up with something that does not sound too harsh.
Member Enumeration Documentation
Interpolator
enum SF2::Render::Sample::Generator::Interpolator strong
Enumerator
linear
cubic4thOrder
Constructor & Destructor Documentation
Generator()
SF2::Render::Sample::Generator::Generator (const CanonicalBuffer & samples, const Voice::State & state, Interpolator kind = Interpolator::linear) inline
Construct a new sample generator.
Parameters
samples source of audio samples
state the generator state to use for rendering
kind the kind of interpolation to perform when generating the render samples
References SF2::Render::Sample::CanonicalBuffer::load().
Member Function Documentation
generate()
double SF2::Render::Sample::Generator::generate (double pitchAdjustment, bool canLoop) inline
Obtain an interpolated sample value at the given index.
Returns
new sample value
References cubic4thOrder, SF2::Render::Sample::Bounds::endIndex(), SF2::Render::Sample::BufferIndex::increment(), SF2::Render::Sample::BufferIndex::index(), linear, and SF2::Render::Sample::BufferIndex::partial().
Referenced by SF2::Render::Voice::Voice::render().
The documentation for this class was generated from the following file:
SoundFontInfoLib/SoundFontInfoLib/Render/Sample/Generator.hpp