SoundFontInfoLib: SF2::Entity::Generator::Definition Class Reference
SF2::Entity::Generator::Definition Class Reference
Meta data for SF2 generators.
#include <Definition.hpp>
Public Types
enum class ValueKind {
unsignedShort = 1 , offset , coarseOffset , signedShort ,
signedCents , signedCentsBel , unsignedPercent , signedPercent ,
signedFrequencyCents , signedTimeCents , signedSemitones , range
}
The kind of value held by the generator.
Public Member Functions
const std::string & name () const
ValueKind valueKind () const
bool isAvailableInPreset () const
bool isUnsignedValue () const
int valueOf (const Amount &amount) const
Obtain the value from a generator Amount instance.
double convertedValueOf (const Amount &amount) const
Obtain the value from a generator Amount instance (from an SF2 file) after converting it to its natural or desired form.
void dump (const Amount &amount) const
Static Public Member Functions
static const Definition & definition (Index index)
Obtain the Definition entry for a given Index value.
Static Public Attributes
static constexpr size_t NumDefs = static_cast<size_t>(Index::numValues)
Detailed Description
Meta data for SF2 generators.
These are attributes associated with a generator but that are not found in an SF2 file. Rather these are attributes called out in the SF2 specification or to make the rendering implementation easier to understand.
Member Enumeration Documentation
ValueKind
enum SF2::Entity::Generator::Definition::ValueKind strong
The kind of value held by the generator.
Enumerator
unsignedShort
offset
coarseOffset
signedShort
signedCents
signedCentsBel
unsignedPercent
signedPercent
signedFrequencyCents
signedTimeCents
signedSemitones
range
Member Function Documentation
convertedValueOf()
double SF2::Entity::Generator::Definition::convertedValueOf (const Amount & amount) const inline
Obtain the value from a generator Amount instance (from an SF2 file) after converting it to its natural or desired form.
Parameters
amount the container holding the value to extract
Returns
the converted value
References SF2::DSP::centsToFrequency(), SF2::DSP::centsToSeconds(), coarseOffset, signedCents, signedCentsBel, signedFrequencyCents, signedPercent, signedTimeCents, unsignedPercent, and valueOf().
Referenced by dump().
definition()
static const Definition& SF2::Entity::Generator::Definition::definition (Index index) inline static
Obtain the Definition entry for a given Index value.
Parameters
index value to lookup
Returns
Definition entry
Referenced by SF2::Render::Voice::State::adjustValue(), SF2::Entity::Generator::Generator::definition(), SF2::Entity::Modulator::Modulator::description(), and SF2::Render::Voice::State::setValue().
dump()
void Definition::dump (const Amount & amount) const
References coarseOffset, convertedValueOf(), SF2::Entity::Generator::Amount::high(), isUnsignedValue(), SF2::Entity::Generator::Amount::low(), offset, range, SF2::Entity::Generator::Amount::signedAmount(), signedCents, signedCentsBel, signedFrequencyCents, signedPercent, signedSemitones, signedShort, signedTimeCents, SF2::Entity::Generator::Amount::unsignedAmount(), unsignedPercent, and unsignedShort.
isAvailableInPreset()
bool SF2::Entity::Generator::Definition::isAvailableInPreset () const inline
Returns
true if the generator can be used in a preset zone
isUnsignedValue()
bool SF2::Entity::Generator::Definition::isUnsignedValue () const inline
Returns
true if the generator amount value is unsigned or signed
References signedShort.
Referenced by dump(), and valueOf().
name()
const std::string& SF2::Entity::Generator::Definition::name () const inline
Returns
name of the definition
Referenced by SF2::Render::Voice::State::adjustValue(), SF2::Entity::Modulator::Modulator::description(), SF2::Entity::Generator::Generator::name(), and SF2::Render::Voice::State::setValue().
valueKind()
ValueKind SF2::Entity::Generator::Definition::valueKind () const inline
Returns
value type of the generator
valueOf()
int SF2::Entity::Generator::Definition::valueOf (const Amount & amount) const inline
Obtain the value from a generator Amount instance.
Properly handles unsigned integer values.
Parameters
amount the container holding the value to extract
Returns
extracted value
References isUnsignedValue(), SF2::Entity::Generator::Amount::signedAmount(), and SF2::Entity::Generator::Amount::unsignedAmount().
Referenced by convertedValueOf(), and SF2::Entity::Generator::Generator::value().
Member Data Documentation
NumDefs
constexpr size_t SF2::Entity::Generator::Definition::NumDefs = static_cast<size_t>(Index::numValues) static constexpr
The documentation for this class was generated from the following files:
SoundFontInfoLib/SoundFontInfoLib/Entity/Generator/Definition.hpp
SoundFontInfoLib/SoundFontInfoLib/Entity/Generator/Definition.cpp