SoundFontInfoLib: SF2::IO Namespace Reference
SF2::IO Namespace Reference
Collection of classes and types involved in parsing an SF2 file or data stream.
Classes
class Chunk
Represents a tagged chunk of a file.
struct ChunkItemsSupport
class ChunkItems
Container of SF2 entities.
class ChunkList
Like Chunk, this class represents a tagged chunk of a file, but this is also a collection of similar items all with the same kind tagged 4-byte value.
class File
Represents an SF2 file.
class Parser
SoundFont file parser.
struct Pos
Representation of a file position.
class Tag
Each RIFF chunk or blob has a 4-character tag that uniquely identifies the contents of the chunk.
Enumerations
enum class Format { RIFF , error }
We only operate with FormatRIFF.
enum Tags {
riff = Pack4Chars("RIFF") , list = Pack4Chars("LIST") , sfbk = Pack4Chars("sfbk") , info = Pack4Chars("INFO") ,
sdta = Pack4Chars("sdta") , pdta = Pack4Chars("pdta") , ifil = Pack4Chars("ifil") , isng = Pack4Chars("isng") ,
inam = Pack4Chars("INAM") , irom = Pack4Chars("irom") , iver = Pack4Chars("iver") , icrd = Pack4Chars("ICRD") ,
ieng = Pack4Chars("IENG") , iprd = Pack4Chars("IPRD") , icop = Pack4Chars("ICOP") , icmt = Pack4Chars("ICMT") ,
istf = Pack4Chars("ISTF") , snam = Pack4Chars("snam") , smpl = Pack4Chars("smpl") , phdr = Pack4Chars("phdr") ,
pbag = Pack4Chars("pbag") , pmod = Pack4Chars("pmod") , pgen = Pack4Chars("pgen") , inst = Pack4Chars("inst") ,
ibag = Pack4Chars("ibag") , imod = Pack4Chars("imod") , igen = Pack4Chars("igen") , shdr = Pack4Chars("shdr") ,
sm24 = Pack4Chars("sm24") , unkn = Pack4Chars("????")
}
Global list of all tags defined in the SF2 specification.
Functions
static void trim_property (char *property, size_t size)
template<typename T >
static void trim_property (T &property)
constexpr uint32_t Pack4Chars (const char *c)
Detailed Description
Collection of classes and types involved in parsing an SF2 file or data stream.
Enumeration Type Documentation
Format
enum SF2::IO::Format strong
We only operate with FormatRIFF.
Enumerator
RIFF
error
Tags
enum SF2::IO::Tags
Global list of all tags defined in the SF2 specification.
Enumerator
riff
list
sfbk
info
sdta
pdta
ifil
isng
inam
irom
iver
icrd
ieng
iprd
icop
icmt
istf
snam
smpl
phdr
pbag
pmod
pgen
inst
ibag
imod
igen
shdr
sm24
unkn
Function Documentation
Pack4Chars()
constexpr uint32_t SF2::IO::Pack4Chars (const char * c) inline constexpr
trim_property() [1/2]
static void SF2::IO::trim_property (char * property, size_t size) inline static
Referenced by SF2::IO::Chunk::extract(), SF2::Entity::Instrument::Instrument(), SF2::Entity::Preset::Preset(), SF2::Entity::SampleHeader::SampleHeader(), and trim_property().
trim_property() [2/2]
template<typename T > static void SF2::IO::trim_property (T & property) inline static
References trim_property().