SoundFontInfoLib: SF2::DSP::Tables::AttenuationLookup Struct Reference
SF2::DSP::Tables::AttenuationLookup Struct Reference
Convert centibels into attenuation via table lookup.
#include <DSPTables.hpp>
Static Public Member Functions
static Float convert (int centibels)
Convert from integer (generator) value to attenuation.
static Float convert (Float centibels)
Convert from floating-point value to attenuation.
Static Public Attributes
constexpr static size_t TableSize = 1441
Friends
struct Generator
Detailed Description
Convert centibels into attenuation via table lookup.
Member Function Documentation
convert() [1/2]
static Float SF2::DSP::Tables::AttenuationLookup::convert (Float centibels) inline static
Convert from floating-point value to attenuation.
Rounds to nearest integer to obtain index.
Parameters
centibels value to convert
References convert().
Referenced by convert().
convert() [2/2]
static Float SF2::DSP::Tables::AttenuationLookup::convert (int centibels) inline static
Convert from integer (generator) value to attenuation.
Parameters
centibels value to convert
References TableSize.
Referenced by SF2::DSP::centibelsToAttenuation().
Friends And Related Function Documentation
Generator
friend struct Generator friend
Member Data Documentation
TableSize
constexpr static size_t SF2::DSP::Tables::AttenuationLookup::TableSize = 1441 inline static constexpr
Referenced by convert().
The documentation for this struct was generated from the following file:
SoundFontInfoLib/SoundFontInfoLib/DSP/DSPTables.hpp