SoundFontInfoLib: SF2::DSP::Tables::CentsFrequencyLookup Struct Reference
SF2::DSP::Tables::CentsFrequencyLookup Struct Reference
Convert cent into frequency multiplier using a table lookup.
#include <DSPTables.hpp>
Static Public Member Functions
static Float convert (int value)
Convert given cents value into a frequency multiplier.
static Float convert (Float value)
Static Public Attributes
constexpr static int Max = 1200
constexpr static size_t TableSize = Max * 2 + 1
Friends
struct Generator
Detailed Description
Convert cent into frequency multiplier using a table lookup.
For instance, to reduce a frequency by -1200 cents means to drop 1 octave which is the same as multiplying the source frequency by 0.5. In the other direction an increase of 1200 cents should result in a multiplier of 2.0 to double the source frequency.
Member Function Documentation
convert() [1/2]
static Float SF2::DSP::Tables::CentsFrequencyLookup::convert (Float value) inline static
References convert().
Referenced by convert().
convert() [2/2]
static Float SF2::DSP::Tables::CentsFrequencyLookup::convert (int value) inline static
Convert given cents value into a frequency multiplier.
Parameters
value the value to convert
Returns
multiplier for a frequency that will change the frequency by the given cent value
References Max.
Referenced by SF2::DSP::centsToFrequencyMultiplier().
Friends And Related Function Documentation
Generator
friend struct Generator friend
Member Data Documentation
Max
constexpr static int SF2::DSP::Tables::CentsFrequencyLookup::Max = 1200 inline static constexpr
Referenced by convert().
TableSize
constexpr static size_t SF2::DSP::Tables::CentsFrequencyLookup::TableSize = Max * 2 + 1 inline static constexpr
The documentation for this struct was generated from the following file:
SoundFontInfoLib/SoundFontInfoLib/DSP/DSPTables.hpp