SoundFontInfoLib: SF2::DSP::Tables::Generator Struct Reference
SF2::DSP::Tables::Generator Struct Reference
Table value generators and initializers.
#include <DSPGenerator.hpp>
Public Member Functions
template<typename T >
void generate (const std::string &name)
Generic table generator.
void generateTransform (std::function< double(int)> proc, const std::string &name, bool bipolar=false)
Generic ValueTransformer table initializer.
void generateCubic4thOrderWeights ()
Generate the weights used for the cubic 4th-order interpolation calculations Based on code found in FluidSynth.
Generator (std::ostream &os)
Public Attributes
std::ostream & os_
Detailed Description
Table value generators and initializers.
This is only used by the DSPGenerators program which creates the DSP tables at compile time for quick loading at runtime.
Constructor & Destructor Documentation
Generator()
Generator::Generator (std::ostream & os)
References generateCubic4thOrderWeights(), generateTransform(), and os_.
Member Function Documentation
generate()
template<typename T > void SF2::DSP::Tables::Generator::generate (const std::string & name) inline
Generic table generator.
The template type T must define a TableSize class parameter that gives the size of the table to initialize, and it must define a Value class method that takes an index value and returns a value to put into the table.
Parameters
name the name of the table to initialize
References os_.
generateCubic4thOrderWeights()
void SF2::DSP::Tables::Generator::generateCubic4thOrderWeights () inline
Generate the weights used for the cubic 4th-order interpolation calculations Based on code found in FluidSynth.
Reordered and normalized to better understand coefficients.
Below is from FluidSynth source (see https://github.com/FluidSynth/fluidsynth/blob/master/src/gentables/gen_rvoice_dsp.c#L25):
Initialize the coefficients for the interpolation. The math comes from a mail, posted by Olli Niemitalo to the music-dsp mailing list (I found it in the music-dsp archives http://www.smartelectronix.com/musicdsp/).
References os_, and SF2::DSP::Tables::Cubic4thOrder::TableSize.
Referenced by Generator().
generateTransform()
void SF2::DSP::Tables::Generator::generateTransform (std::function< double(int)> proc, const std::string & name, bool bipolar = false) inline
Generic ValueTransformer table initializer.
Parameters
proc the function that generates a value for a given table index
name the table name to initialize
bipolar if true, initialize a bipolar table; otherwise, a unipolar one (default).
References os_, SF2::MIDI::ValueTransformer::TableSize, and SF2::DSP::unipolarToBipolar().
Referenced by Generator().
Member Data Documentation
os_
std::ostream& SF2::DSP::Tables::Generator::os_
Referenced by generate(), generateCubic4thOrderWeights(), generateTransform(), and Generator().
The documentation for this struct was generated from the following files:
SoundFontInfoLib/SoundFontInfoLib/DSP/DSPGenerator.hpp
SoundFontInfoLib/DSPGenerator/DSPGenerator.cc