SoundFontInfoLib: SF2::Render::Sample::BufferIndex Struct Reference
SF2::Render::Sample::BufferIndex Struct Reference
Interpolatable index into a CanonicalBuffer.
#include <BufferIndex.hpp>
Public Member Functions
BufferIndex (const Bounds &bounds)
void setIncrement (double increment)
Set the increment to use when advancing the index.
bool hasIncrement () const
void increment (const Bounds &bounds, bool canLoop)
Increment the index to the next location.
size_t index () const
double partial () const
bool finished () const
Detailed Description
Interpolatable index into a CanonicalBuffer.
Maintains two counters, an integral one (size_t) and a partial one (double) that indicates how close the index is to a sample index. These two values are then used by SampleBuffer routines to fetch the correct samples and interpolate over them.
Updates to the index honor loops in the sample stream if allowed. The index can also signal when it has reached the end of the sample stream via its finished method.
Constructor & Destructor Documentation
BufferIndex()
SF2::Render::Sample::BufferIndex::BufferIndex (const Bounds & bounds) inline
Member Function Documentation
finished()
bool SF2::Render::Sample::BufferIndex::finished () const inline
Returns
true if the index is no longer moving
Referenced by increment().
hasIncrement()
bool SF2::Render::Sample::BufferIndex::hasIncrement () const inline
increment()
void SF2::Render::Sample::BufferIndex::increment (const Bounds & bounds, bool canLoop) inline
Increment the index to the next location.
Properly handles looping and buffer end.
Parameters
bounds current boundaries and loop point for the sample being indexed
canLoop true if looping is allowed
References bounds, SF2::Logger::debug(), and finished().
Referenced by SF2::Render::Sample::Generator::generate(), and setIncrement().
index()
size_t SF2::Render::Sample::BufferIndex::index () const inline
Returns
index to first sample to use for rendering
Referenced by SF2::Render::Sample::Generator::generate().
partial()
double SF2::Render::Sample::BufferIndex::partial () const inline
Returns
normalized position between 2 samples. For instance, 0.5 indicates half-way between two samples.
Referenced by SF2::Render::Sample::Generator::generate().
setIncrement()
void SF2::Render::Sample::BufferIndex::setIncrement (double increment) inline
Set the increment to use when advancing the index.
This can change with each sample depending on what modulators are doing with the pitch value (eg vibrato).
Parameters
increment the value to apply when advancing the index
References increment().
The documentation for this struct was generated from the following file:
SoundFontInfoLib/SoundFontInfoLib/Render/Sample/BufferIndex.hpp