name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SNAPSHOT_ARTIFACTS: ${{ github.workspace }}/snapshots
  TEST_RUNNER_SNAPSHOT_ARTIFACTS: ${{ github.workspace }}/snapshots

jobs:
  build:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 16.1
      run: ls -l /Applications && sudo xcode-select -s /APplications/Xcode_16.1.app
    - name: Build, test, and code coverage
      run: env && make
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: 61c608b414893498479c268f2a106292
        filename: SoundFonts-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
