#!/bin/env python

import glob, os, string, sys
from sf2utils.sf2parse import Sf2File
from datetime import date

def run(filePaths):
    '''
        Generate *.swift files for each SoundFont (sf2) file in the current directory.
        The Swift files will contain a custom SoundFont definition that lists all of
        the patches found in the SF2 file.
    '''

    registrations = ''

    for filePath in filePaths:
        print "...processing", filePath

        # Load the SF2 file and get the patches / presets in it
        with open(filePath, 'rb') as sf2File:

            sf2 = Sf2File(sf2File)
            presets = [(getattr(z, 'bank', None), getattr(z, 'preset', None), getattr(z, 'name', None))
                       for z in sf2.presets]
            if presets[-1][0] == None:
                del presets[-1]
            presets.sort()
            print "...found", len(presets), "presets in file"

            # Generate the Swift file with the SoundFont definition for the SF2 file
            filePath = os.path.basename(os.path.splitext(filePath)[0])
            valid = string.letters + string.digits + '_'
            name = filter(lambda a: a in valid, sf2.info.bank_name)

            registrations += '{}SoundFont.name: {}SoundFont,\n'.format(name, name)

            # Generate a header for the file and then write out all of the preset names
            year = date.today().year
            with open('./' + filePath + '.swift', 'w') as swiftFile:
                swiftFile.write('''//
// SoundFont
//
// Created by Brad Howes
// Copyright (c) {} Brad Howes. All rights reserved.
//
// NOTE: this file was autogenerated by the `catalog.py` script.

let {}SoundFont = SoundFont("{}", fileName: "{}", [
'''.format(year, name, sf2.info.bank_name, filePath))
                for index, each in enumerate(presets):
                    swiftFile.write('    Patch({:30} {:3d}, {:3d}, {:3d}),\n'
                                    .format('"' + each[2] + '",', each[0], each[1], index))
                swiftFile.write('])\n')

    # Now that we have processed all of the SF2 files, update the ../SoundFont.swift file so that it
    # knows about all of the SF2 patches. Read in the current file.
    print "...updating ../SoundFont.swift file"
    with open('../SoundFont.swift', 'r') as sf:
        contents = sf.read()

    # Replace all of the current lines between BEGIN and END comments with the contents
    # of `registrations` that was generated above
    begin = contents.find('// -BEGIN-')
    if begin == -1: raise "*** missing '// -BEGIN-' token in SoundFont.swift file"
    end = contents.find('// -END-')
    if end == -1: raise "*** missing '// -END-' token in SoundFont.swift file"
    contents = contents[:begin] + '// -BEGIN-\n' + registrations + contents[end:]

    with open('../SoundFont.swift', 'w') as sf:
        sf.write(contents)

    print("...done")

if __name__ == '__main__':
    run(glob.glob('./*.sf2'))
